In [1]:
!pip install pandas

Looking in indexes: http://mirrors.aliyun.com/pypi/simple


In [2]:
!pip install scikit-learn

Looking in indexes: http://mirrors.aliyun.com/pypi/simple


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader 
from sklearn.neighbors import KNeighborsClassifier

In [4]:
data=pd.read_csv("train.csv")

In [5]:
data=pd.read_csv("train.csv")
data_test=pd.read_csv("testA.csv")
data.head()

id                                  heartbeat_signals  label
0   0  0.9912297987616655,0.9435330436439665,0.764677...    0.0
1   1  0.9714822034884503,0.9289687459588268,0.572932...    0.0
2   2  1.0,0.9591487564065292,0.7013782792997189,0.23...    2.0
3   3  0.9757952826275774,0.9340884687738161,0.659636...    0.0
4   4  0.0,0.055816398940721094,0.26129357194994196,0...    2.0

In [6]:
# 数据处理
data_1=data["heartbeat_signals"].str.split(",", expand=True)
data_test_1=data_test["heartbeat_signals"].str.split(",", expand=True)
data_1

0                     1                    2    \
0      0.9912297987616655    0.9435330436439665   0.7646772997256593   
1      0.9714822034884503    0.9289687459588268   0.5729328050711678   
2                     1.0    0.9591487564065292   0.7013782792997189   
3      0.9757952826275774    0.9340884687738161   0.6596366611990001   
4                     0.0  0.055816398940721094  0.26129357194994196   
...                   ...                   ...                  ...   
99995                 1.0     0.677705342021188  0.22239242747868546   
99996  0.9268571578157265    0.9063471198026871   0.6369932212888393   
99997  0.9258351628306013    0.5873839035878395   0.6332261741951388   
99998                 1.0    0.9947621698382489   0.8297017704865509   
99999  0.9259994004527861     0.916476635326053   0.4042900774399834   

                       3                    4                    5    \
0       0.6185708990212999   0.3796321642826237  0.19082233510621885   
1       0.1784566262750076   0.1229615224365985  0.13236021729815928   
2      0.23177753487886463                  0.0  0.08069805776387916   
3       0.2499208267606008  0.23711575621286213  0.28144491730834825   
4      0.35984696254197834  0.43314263962884686  0.45369772898632504   
...                    ...                  ...                  ...   
99995   0.2571578307224994  0.20469042415279454  0.05466497618736314   
99996  0.41503751002775946  0.37474480119929776   0.3825812845814957   
99997   0.6323533645350808   0.6392827243034813   0.6142923239940205   
99998  0.45819277171637834  0.26416169623741237  0.24022845026183584   
99999                  0.0   0.2630344094167657   0.3854310437765884   

                        6                    7                     8    \
0      0.040237131594430715  0.02599520771717858   0.03170886048677242   
1       0.09439236984499814  0.08957535516351411  0.030480606866741047   
2       0.12837603937503544  0.18744837555079963   0.28082571505275855   
3        0.2499208267606008   0.2499208267606008   0.24139674778512604   
4       0.49900406742109477   0.5427959768500487    0.6169044962835193   
...                     ...                  ...                   ...   
99995  0.026152286890497062  0.11818142707296006   0.24483757081121627   
99996   0.35894293360916163  0.34135861850914284    0.3365254578264915   
99997    0.5991551019747257   0.5176324324889339    0.4038033525475481   
99998   0.21376575735540573  0.18929103849637752   0.20381573166587716   
99999    0.3610665021846972  0.33270794046870034   0.33985000288462475   

                       9    ...  195  196  197  198  199  200  201  202  203  \
0      0.06552357497104398  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1      0.04049936195430977  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2       0.3282610568488903  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3       0.2306703464848836  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4       0.6766958323316207  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995   0.3289485158861968  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99996   0.3170292884548231  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99997   0.2531748788594435  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99998  0.21086610220048516  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
99999   0.3504972538285509  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

       204  
0      0.0  
1      0.0  
2      0.0  
3      0.0  
4      0.0  
...    ...  
99995  0.0  
99996  0.0  
99997  0.0  
99998  0.0  
99999  0.0  

[100000 rows x 205 columns]

In [7]:
np.array(data.label)

array([0., 0., 2., ..., 3., 2., 0.])

In [8]:
data_2 = np.array(data_1).astype("float32").reshape(-1,1,205)
data_test_2= np.array(data_test_1).astype("float32").reshape(-1,1,205)
data_2

array([[[0.9912298 , 0.94353306, 0.7646773 , ..., 0.        ,
         0.        , 0.        ]],

       [[0.9714822 , 0.9289687 , 0.5729328 , ..., 0.        ,
         0.        , 0.        ]],

       [[1.        , 0.95914876, 0.7013783 , ..., 0.        ,
         0.        , 0.        ]],

       ...,

       [[0.9258352 , 0.5873839 , 0.63322616, ..., 0.        ,
         0.        , 0.        ]],

       [[1.        , 0.9947622 , 0.8297018 , ..., 0.        ,
         0.        , 0.        ]],

       [[0.9259994 , 0.9164766 , 0.40429008, ..., 0.        ,
         0.        , 0.        ]]], dtype=float32)

In [9]:
torch.set_printoptions(precision=7)
x_train=torch.tensor(data_2)
x_test=torch.tensor(data_test_2)
y_train=torch.tensor(data.label,dtype=int)
x_train

/tmp/ipykernel_816/3417645431.py:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  y_train=torch.tensor(data.label,dtype=int)


tensor([[[0.9912298, 0.9435331, 0.7646773,  ..., 0.0000000, 0.0000000,
          0.0000000]],

        [[0.9714822, 0.9289687, 0.5729328,  ..., 0.0000000, 0.0000000,
          0.0000000]],

        [[1.0000000, 0.9591488, 0.7013783,  ..., 0.0000000, 0.0000000,
          0.0000000]],

        ...,

        [[0.9258352, 0.5873839, 0.6332262,  ..., 0.0000000, 0.0000000,
          0.0000000]],

        [[1.0000000, 0.9947622, 0.8297018,  ..., 0.0000000, 0.0000000,
          0.0000000]],

        [[0.9259994, 0.9164766, 0.4042901,  ..., 0.0000000, 0.0000000,
          0.0000000]]])

In [10]:
x_train.shape

torch.Size([100000, 1, 205])

In [11]:
# 数据转移至GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

x_train=x_train.to(device)
y_train=y_train.to(device)
x_test=x_test.to(device)

cuda


In [12]:
!nvidia-smi


Fri Jun  7 15:43:28 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:40:00.0 Off |                  N/A |
| 47%   41C    P2    80W / 320W |   2073MiB / 10240MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [13]:
dataset = TensorDataset(x_train, y_train)
dataset

In [14]:
train_loader = DataLoader(dataset, batch_size=128, shuffle=True)
test_loader = DataLoader(x_test, batch_size=128, shuffle=True)
train_loader

In [15]:
len(train_loader) #DataLoader会将一个epoch按照bitch_size大小分为多少批次

782

In [16]:
# 定义模型
class CNN_1(nn.Module):

    def __init__(self):
        super(CNN_1,self).__init__()
        self.conv1 = nn.Conv1d(in_channels = 1,out_channels = 64,kernel_size = 7,stride = 1,padding = 3)
        self.conv2 = nn.Conv1d(in_channels = 64,out_channels = 128,kernel_size = 5,stride = 1,padding = 2)
        self.conv3 = nn.Conv1d(in_channels = 128,out_channels = 256,kernel_size = 3,stride = 1,padding = 1)
        self.conv4 = nn.Conv1d(in_channels = 256,out_channels = 256,kernel_size = 3,stride = 1,padding = 1)
        self.maxpool = nn.MaxPool1d(kernel_size = 2)
        self.sleakyrelu = nn.LeakyReLU(negative_slope = 0.05)
        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(128)
        self.bn3 = nn.BatchNorm1d(256)
        self.bn4 = nn.BatchNorm1d(256)
        self.dropout=nn.Dropout(0.2)
        
        self.linear = nn.Sequential(
            nn.Linear(6400, 4096),
            nn.BatchNorm1d(4096),
            nn.LeakyReLU(negative_slope = 0.05),
            nn.Linear(4096, 64),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(negative_slope = 0.05),
            nn.Linear(64, 4)
        )

    def forward(self,x):
        x = self.bn1(self.conv1(x))
        x = self.sleakyrelu(x)
        x = self.maxpool(x)
        x = self.bn2(self.conv2(x))
        x = self.sleakyrelu(x)
        x = self.maxpool(x)
        x = self.bn3(self.conv3(x))
        x = self.sleakyrelu(x)
        x = self.bn4(self.conv4(x))
        x = self.sleakyrelu(x)
        x = self.maxpool(x)
        x = self.dropout(x)
        x = torch.flatten(x,start_dim=1)
        x = self.linear(x)
        return x
    
    
    
class CNN_2(nn.Module):
    def __init__(self):
        super(CNN_2, self).__init__()
        self.conv = nn.Sequential(
            nn.Conv1d(in_channels = 1,out_channels = 16,kernel_size = 11,stride =1 ,padding = 'same'), 
            nn.BatchNorm1d(16),
            nn.LeakyReLU(), 
            
            nn.Conv1d(in_channels = 16,out_channels = 32,kernel_size = 7,stride = 1,padding = 'same'),
            nn.BatchNorm1d(32),
            nn.LeakyReLU(),
            
            nn.Conv1d(in_channels = 32,out_channels = 64,kernel_size = 5,stride = 1,padding = 1),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(),
            nn.MaxPool1d(kernel_size = 3, stride = 2),
            
            nn.Conv1d(in_channels = 64,out_channels = 128,kernel_size = 3,stride = 1,padding = 1),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(),
            
            nn.Conv1d(in_channels = 128,out_channels = 128,kernel_size = 3,stride = 1,padding = 1),
            nn.BatchNorm1d(128),
            nn.LeakyReLU(),
            nn.MaxPool1d(kernel_size= 3, stride = 2),
            nn.Dropout(0.2)
        )
        self.linear = nn.Sequential(
            nn.Linear(6400,4096),
            nn.BatchNorm1d(4096),
            nn.LeakyReLU(),
            nn.Linear(4096, 64),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(),
            nn.Linear(64, 4),
        )

    def forward(self, x):
        x = self.conv(x)
        x = torch.flatten(x,start_dim=1)
        x = self.linear(x)
        return x

    

In [17]:


class SEBlock(nn.Module):
    def __init__(self, in_channels, reduction=16):
        super(SEBlock, self).__init__()
        self.fc1 = nn.Linear(in_channels, in_channels // reduction, bias=False)
        self.fc2 = nn.Linear(in_channels // reduction, in_channels, bias=False)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        batch_size, num_channels, _ = x.size()
        squeeze = x.mean(-1)
        excitation = self.fc1(squeeze)
        excitation = self.relu(excitation)
        excitation = self.fc2(excitation)
        excitation = self.sigmoid(excitation).view(batch_size, num_channels, 1)
        return x * excitation

class SENet(nn.Module):
    def __init__(self):
        super(SENet, self).__init__()
        self.conv1 = nn.Conv1d(in_channels=1, out_channels=64, kernel_size=7, stride=1, padding=3)
        self.se1 = SEBlock(64)
        self.conv2 = nn.Conv1d(in_channels=64, out_channels=128, kernel_size=5, stride=1, padding=2)
        self.se2 = SEBlock(128)
        self.conv3 = nn.Conv1d(in_channels=128, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.se3 = SEBlock(256)
        self.conv4 = nn.Conv1d(in_channels=256, out_channels=256, kernel_size=3, stride=1, padding=1)
        self.se4 = SEBlock(256)
        self.maxpool = nn.MaxPool1d(kernel_size=2)
        self.leakyrelu = nn.LeakyReLU(negative_slope=0.05)
        self.bn1 = nn.BatchNorm1d(64)
        self.bn2 = nn.BatchNorm1d(128)
        self.bn3 = nn.BatchNorm1d(256)
        self.bn4 = nn.BatchNorm1d(256)
        self.dropout = nn.Dropout(0.2)
        
        self.linear = nn.Sequential(
            nn.Linear(6400, 4096),
            nn.BatchNorm1d(4096),
            nn.LeakyReLU(negative_slope=0.05),
            nn.Linear(4096, 64),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(negative_slope=0.05),
            nn.Linear(64, 4)
        )

    def forward(self, x):
        x = self.bn1(self.conv1(x))
        x = self.se1(x)
        x = self.leakyrelu(x)
        x = self.maxpool(x)
        x = self.bn2(self.conv2(x))
        x = self.se2(x)
        x = self.leakyrelu(x)
        x = self.maxpool(x)
        x = self.bn3(self.conv3(x))
        x = self.se3(x)
        x = self.leakyrelu(x)
        x = self.bn4(self.conv4(x))
        x = self.se4(x)
        x = self.leakyrelu(x)
        x = self.maxpool(x)
        x = self.dropout(x)
        x = torch.flatten(x, start_dim=1)
        x = self.linear(x)
        return x


In [21]:
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
import torch.nn as nn

# 初始化模型
model_senet = SENet()

# 权值初始化
for m in model_senet.modules():
    if isinstance(m, nn.Conv1d):
        nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
    elif isinstance(m, nn.Linear):
        nn.init.xavier_normal_(m.weight)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_senet.parameters(), lr=0.00001)
scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=5, verbose=True)

model_senet.to(device)

num_epochs = 80
early_stopping_patience = 10
best_loss = float('inf')
patience_counter = 0

# 全训练集训练
for epoch in range(num_epochs):
    model_senet.train()
    running_loss = 0.0
    for inputs, targets in train_loader:
        inputs, targets = inputs.to(device), targets.to(device)
        
        # 前向传播
        outputs = model_senet(inputs)
        loss = criterion(outputs, targets)
        
        # 反向传播和优化
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
    train_loss = running_loss / len(train_loader)
    
    print('Epoch: {}, train_loss: {:.2e}'.format(epoch + 1, train_loss))
    
    # 动态学习率调整
    scheduler.step(train_loss)
    
    # 早停机制
    if train_loss < best_loss:
        best_loss = train_loss
        patience_counter = 0
    else:
        patience_counter += 1
        if patience_counter >= early_stopping_patience:
            print("Early stopping at epoch:", epoch + 1)
            break


Epoch: 1, train_loss: 3.73e-01
Epoch: 2, train_loss: 1.84e-01
Epoch: 3, train_loss: 1.35e-01
Epoch: 4, train_loss: 1.05e-01
Epoch: 5, train_loss: 8.53e-02
Epoch: 6, train_loss: 6.98e-02
Epoch: 7, train_loss: 5.81e-02
Epoch: 8, train_loss: 4.85e-02
Epoch: 9, train_loss: 4.08e-02
Epoch: 10, train_loss: 3.51e-02
Epoch: 11, train_loss: 2.99e-02
Epoch: 12, train_loss: 2.61e-02
Epoch: 13, train_loss: 2.25e-02
Epoch: 14, train_loss: 1.97e-02
Epoch: 15, train_loss: 1.71e-02
Epoch: 16, train_loss: 1.48e-02
Epoch: 17, train_loss: 1.33e-02
Epoch: 18, train_loss: 1.19e-02
Epoch: 19, train_loss: 1.06e-02
Epoch: 20, train_loss: 9.62e-03
Epoch: 21, train_loss: 8.59e-03
Epoch: 22, train_loss: 7.63e-03
Epoch: 23, train_loss: 6.73e-03
Epoch: 24, train_loss: 6.14e-03
Epoch: 25, train_loss: 5.52e-03
Epoch: 26, train_loss: 5.34e-03
Epoch: 27, train_loss: 5.00e-03
Epoch: 28, train_loss: 4.35e-03
Epoch: 29, train_loss: 4.02e-03
Epoch: 30, train_loss: 3.79e-03
Epoch: 31, train_loss: 3.62e-03
Epoch: 32, train_

In [18]:
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
import torch.nn as nn

# 初始化模型、损失函数和优化器
model_1 = CNN_1()
# model_2 = CNN_2()

# 权值初始化
for m in model_1.modules():
    if isinstance(m, nn.Conv1d):
        nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
    elif isinstance(m, nn.Linear):
        nn.init.xavier_normal_(m.weight)
        
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_1.parameters(), lr=0.00001)
scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=5, verbose=True)

model_1.to(device)

num_epochs = 150
early_stopping_patience = 10
best_loss = float('inf')
patience_counter = 0

# 全训练集训练
for epoch in range(num_epochs): 
    model_1.train()
    running_loss = 0.0
    for inputs, targets in train_loader: 
        inputs, targets = inputs.to(device), targets.to(device)
        
        # 前向传播
        outputs = model_1(inputs)
        loss = criterion(outputs, targets)
        
        # 反向传播和优化
        optimizer.zero_grad()
        loss.backward()
        optimizer.step() 
        
        running_loss += loss.item()
    train_loss = running_loss / len(train_loader)
    
    print('Epoch: {}, train_loss: {:.2e}'.format(epoch + 1, train_loss))
    
    # 动态学习率调整
    scheduler.step(train_loss)
    
    # 早停机制
    if train_loss < best_loss:
        best_loss = train_loss
        patience_counter = 0
    else:
        patience_counter += 1
        if patience_counter >= early_stopping_patience:
            print("Early stopping at epoch:", epoch + 1)
            break


Epoch: 1, train_loss: 2.43e-01
Epoch: 2, train_loss: 1.22e-01
Epoch: 3, train_loss: 9.22e-02
Epoch: 4, train_loss: 7.46e-02
Epoch: 5, train_loss: 6.21e-02
Epoch: 6, train_loss: 5.19e-02
Epoch: 7, train_loss: 4.51e-02
Epoch: 8, train_loss: 3.85e-02
Epoch: 9, train_loss: 3.32e-02
Epoch: 10, train_loss: 2.92e-02
Epoch: 11, train_loss: 2.56e-02
Epoch: 12, train_loss: 2.25e-02
Epoch: 13, train_loss: 1.97e-02
Epoch: 14, train_loss: 1.76e-02
Epoch: 15, train_loss: 1.58e-02
Epoch: 16, train_loss: 1.40e-02
Epoch: 17, train_loss: 1.26e-02
Epoch: 18, train_loss: 1.08e-02
Epoch: 19, train_loss: 1.01e-02
Epoch: 20, train_loss: 9.23e-03
Epoch: 21, train_loss: 7.96e-03
Epoch: 22, train_loss: 7.54e-03
Epoch: 23, train_loss: 6.67e-03
Epoch: 24, train_loss: 6.03e-03
Epoch: 25, train_loss: 5.85e-03
Epoch: 26, train_loss: 5.24e-03
Epoch: 27, train_loss: 5.02e-03
Epoch: 28, train_loss: 4.51e-03
Epoch: 29, train_loss: 3.95e-03
Epoch: 30, train_loss: 3.81e-03
Epoch: 31, train_loss: 3.45e-03
Epoch: 32, train_

In [19]:
import torch.optim as optim
from torch.optim.lr_scheduler import ReduceLROnPlateau
import torch.nn as nn

# 初始化模型、损失函数和优化器
# model_1 = CNN_1()
model_2 = CNN_2()

# 权值初始化
for m in model_2.modules():
    if isinstance(m, nn.Conv1d):
        nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
    elif isinstance(m, nn.Linear):
        nn.init.xavier_normal_(m.weight)
        
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_2.parameters(), lr=0.00001)
scheduler = ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=5, verbose=True)

model_2.to(device)

num_epochs = 150
early_stopping_patience = 10
best_loss = float('inf')
patience_counter = 0

# 全训练集训练
for epoch in range(num_epochs): 
    model_2.train()
    running_loss = 0.0
    for inputs, targets in train_loader: 
        inputs, targets = inputs.to(device), targets.to(device)
        
        # 前向传播
        outputs = model_2(inputs)
        loss = criterion(outputs, targets)
        
        # 反向传播和优化
        optimizer.zero_grad()
        loss.backward()
        optimizer.step() 
        
        running_loss += loss.item()
    train_loss = running_loss / len(train_loader)
    
    print('Epoch: {}, train_loss: {:.2e}'.format(epoch + 1, train_loss))
    
    # 动态学习率调整
    scheduler.step(train_loss)
    
    # 早停机制
    if train_loss < best_loss:
        best_loss = train_loss
        patience_counter = 0
    else:
        patience_counter += 1
        if patience_counter >= early_stopping_patience:
            print("Early stopping at epoch:", epoch + 1)
            break


Epoch: 1, train_loss: 2.89e-01
Epoch: 2, train_loss: 1.43e-01
Epoch: 3, train_loss: 1.08e-01
Epoch: 4, train_loss: 8.56e-02
Epoch: 5, train_loss: 7.00e-02
Epoch: 6, train_loss: 5.83e-02
Epoch: 7, train_loss: 4.92e-02
Epoch: 8, train_loss: 4.12e-02
Epoch: 9, train_loss: 3.53e-02
Epoch: 10, train_loss: 2.99e-02
Epoch: 11, train_loss: 2.59e-02
Epoch: 12, train_loss: 2.25e-02
Epoch: 13, train_loss: 1.94e-02
Epoch: 14, train_loss: 1.70e-02
Epoch: 15, train_loss: 1.50e-02
Epoch: 16, train_loss: 1.30e-02
Epoch: 17, train_loss: 1.15e-02
Epoch: 18, train_loss: 1.03e-02
Epoch: 19, train_loss: 9.07e-03
Epoch: 20, train_loss: 7.85e-03
Epoch: 21, train_loss: 7.53e-03
Epoch: 22, train_loss: 6.59e-03
Epoch: 23, train_loss: 5.89e-03
Epoch: 24, train_loss: 4.94e-03
Epoch: 25, train_loss: 4.75e-03
Epoch: 26, train_loss: 4.35e-03
Epoch: 27, train_loss: 3.61e-03
Epoch: 28, train_loss: 3.74e-03
Epoch: 29, train_loss: 3.23e-03
Epoch: 30, train_loss: 3.35e-03
Epoch: 31, train_loss: 2.86e-03
Epoch: 32, train_

## 下面没有加早停和动态学习率

In [19]:
# import torch.optim as optim

# # 初始化模型
# model_senet = SENet()

# # 权值初始化
# for m in model_senet.modules():
#     if isinstance(m, nn.Conv1d):
#         nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
#     elif isinstance(m, nn.Linear):
#         nn.init.xavier_normal_(m.weight)

# criterion = nn.CrossEntropyLoss()
# optimizer = optim.Adam(model_senet.parameters(), lr=0.00001)

# model_senet.to(device)

# num_epochs = 50

# # 全训练集训练
# for epoch in range(num_epochs):
#     model_senet.train()
#     running_loss = 0.0
#     for inputs, targets in train_loader:
#         inputs, targets = inputs.to(device), targets.to(device)
        
#         # 前向传播
#         outputs = model_senet(inputs)
#         loss = criterion(outputs, targets)
        
#         # 反向传播和优化
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step()
        
#         running_loss += loss.item()
#     train_loss = running_loss / 100000
    
#     print('Epoch: {}, train_loss: {:.2e}'.format(epoch + 1, loss.item()))


Epoch: 1, train_loss: 2.01e-01
Epoch: 2, train_loss: 2.46e-01
Epoch: 3, train_loss: 3.38e-02
Epoch: 4, train_loss: 1.00e-01
Epoch: 5, train_loss: 1.86e-01
Epoch: 6, train_loss: 1.90e-02
Epoch: 7, train_loss: 5.07e-02
Epoch: 8, train_loss: 3.84e-02
Epoch: 9, train_loss: 5.82e-02
Epoch: 10, train_loss: 7.14e-02
Epoch: 11, train_loss: 1.86e-02
Epoch: 12, train_loss: 4.12e-03
Epoch: 13, train_loss: 1.26e-02
Epoch: 14, train_loss: 1.35e-01
Epoch: 15, train_loss: 1.51e-02
Epoch: 16, train_loss: 2.57e-02
Epoch: 17, train_loss: 1.53e-02
Epoch: 18, train_loss: 7.82e-02
Epoch: 19, train_loss: 1.88e-02
Epoch: 20, train_loss: 3.55e-03
Epoch: 21, train_loss: 5.43e-03
Epoch: 22, train_loss: 7.61e-03
Epoch: 23, train_loss: 5.14e-02
Epoch: 24, train_loss: 7.47e-03
Epoch: 25, train_loss: 2.22e-02
Epoch: 26, train_loss: 3.59e-03
Epoch: 27, train_loss: 2.50e-02
Epoch: 28, train_loss: 9.79e-04
Epoch: 29, train_loss: 1.13e-03
Epoch: 30, train_loss: 5.27e-03
Epoch: 31, train_loss: 6.35e-04
Epoch: 32, train_

In [20]:
# # 初始化模型、损失函数和优化器

# model_1 = CNN_1()
# # model_2 = CNN_2()


# #权值初始化
# for m in model_1.modules():
#     if isinstance(m, nn.Conv1d):
#         nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
#     elif isinstance(m, nn.Linear):
#         nn.init.xavier_normal_(m.weight)
        
# criterion = nn.CrossEntropyLoss()
# optimizer = optim.Adam(model_1.parameters(), lr=0.00001)

# model_1.to(device)

# num_epochs=40
  
# # 全训练集训练
# for epoch in range(num_epochs): 
#     model_1.train()
#     running_loss=0.0
#     for inputs, targets in train_loader: 
        
#         # 前向传播
#         outputs = model_1(inputs)
#         loss = criterion(outputs, targets)
#         # 反向传播和优化
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step() 
#         running_loss += loss.item()
#     train_loss = running_loss/100000
    
#     print('Epoch:{}, train_loss: {:.2e}'.format(epoch+1, loss.item()))
    
#     # 验证数据   
# ''' model.eval()
#     with torch.no_grad():
#         val_loss = 0.0
#         for val_inputs, val_targets in val_loader:
#             val_outputs = model(val_inputs)
#             val_loss += criterion(val_outputs, val_targets).item()
   
#         val_loss /= len(dataset_2)
    
#         print('Epoch: {}, Train Loss: {:.2e}, Val Loss: {:.2e}'.format(epoch+1, loss.item(), val_loss))'''
      

Epoch:1, train_loss: 7.07e-02
Epoch:2, train_loss: 1.10e-01
Epoch:3, train_loss: 5.07e-02
Epoch:4, train_loss: 3.66e-02
Epoch:5, train_loss: 4.21e-02
Epoch:6, train_loss: 6.49e-02
Epoch:7, train_loss: 1.74e-01
Epoch:8, train_loss: 7.07e-02
Epoch:9, train_loss: 3.30e-02
Epoch:10, train_loss: 6.61e-02
Epoch:11, train_loss: 3.11e-02
Epoch:12, train_loss: 2.26e-02
Epoch:13, train_loss: 9.85e-03
Epoch:14, train_loss: 5.29e-02
Epoch:15, train_loss: 2.90e-02
Epoch:16, train_loss: 3.90e-03
Epoch:17, train_loss: 3.93e-03
Epoch:18, train_loss: 3.84e-02
Epoch:19, train_loss: 8.19e-03
Epoch:20, train_loss: 1.27e-02
Epoch:21, train_loss: 1.09e-02
Epoch:22, train_loss: 6.10e-03
Epoch:23, train_loss: 2.25e-03
Epoch:24, train_loss: 1.97e-03
Epoch:25, train_loss: 8.31e-03
Epoch:26, train_loss: 1.54e-02
Epoch:27, train_loss: 3.39e-03
Epoch:28, train_loss: 1.08e-02
Epoch:29, train_loss: 1.68e-03
Epoch:30, train_loss: 1.04e-02
Epoch:31, train_loss: 3.06e-03
Epoch:32, train_loss: 1.15e-02
Epoch:33, train_l

" model.eval()\n    with torch.no_grad():\n        val_loss = 0.0\n        for val_inputs, val_targets in val_loader:\n            val_outputs = model(val_inputs)\n            val_loss += criterion(val_outputs, val_targets).item()\n   \n        val_loss /= len(dataset_2)\n    \n        print('Epoch: {}, Train Loss: {:.2e}, Val Loss: {:.2e}'.format(epoch+1, loss.item(), val_loss))"

In [21]:
# # 初始化模型、损失函数和优化器

# # model_1 = CNN_1()
# model_2 = CNN_2()


# #权值初始化
# for m in model_2.modules():
#     if isinstance(m, nn.Conv1d):
#         nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
#     elif isinstance(m, nn.Linear):
#         nn.init.xavier_normal_(m.weight)
        
# criterion = nn.CrossEntropyLoss()
# optimizer = optim.Adam(model_2.parameters(), lr=0.00001)

# model_2.to(device)

# num_epochs=40
  
# # 全训练集训练
# for epoch in range(num_epochs): 
#     model_2.train()
#     running_loss=0.0
#     for inputs, targets in train_loader: 
#         # 前向传播
#         outputs = model_2(inputs)
#         loss = criterion(outputs, targets)
#         # 反向传播和优化
#         optimizer.zero_grad()
#         loss.backward()
#         optimizer.step() 
#         running_loss += loss.item()
#     train_loss = running_loss/100000
    
#     print('Epoch:{}, train_loss: {:.2e}'.format(epoch+1, loss.item()))
    
#     # 验证数据   
# ''' model.eval()
#     with torch.no_grad():
#         val_loss = 0.0
#         for val_inputs, val_targets in val_loader:
#             val_outputs = model(val_inputs)
#             val_loss += criterion(val_outputs, val_targets).item()
   
#         val_loss /= len(dataset_2)
    
#         print('Epoch: {}, Train Loss: {:.2e}, Val Loss: {:.2e}'.format(epoch+1, loss.item(), val_loss))'''
      

Epoch:1, train_loss: 2.10e-01
Epoch:2, train_loss: 1.75e-01
Epoch:3, train_loss: 1.23e-01
Epoch:4, train_loss: 6.57e-02
Epoch:5, train_loss: 1.19e-01
Epoch:6, train_loss: 3.98e-02
Epoch:7, train_loss: 6.62e-02
Epoch:8, train_loss: 5.45e-02
Epoch:9, train_loss: 3.69e-02
Epoch:10, train_loss: 1.81e-02
Epoch:11, train_loss: 1.08e-02
Epoch:12, train_loss: 1.99e-02
Epoch:13, train_loss: 4.18e-02
Epoch:14, train_loss: 1.96e-02
Epoch:15, train_loss: 9.09e-03
Epoch:16, train_loss: 7.63e-03
Epoch:17, train_loss: 1.09e-02
Epoch:18, train_loss: 8.02e-03
Epoch:19, train_loss: 7.52e-03
Epoch:20, train_loss: 4.56e-03
Epoch:21, train_loss: 5.00e-03
Epoch:22, train_loss: 7.90e-02
Epoch:23, train_loss: 8.87e-03
Epoch:24, train_loss: 1.01e-02
Epoch:25, train_loss: 2.13e-03
Epoch:26, train_loss: 5.87e-03
Epoch:27, train_loss: 9.11e-03
Epoch:28, train_loss: 7.11e-03
Epoch:29, train_loss: 2.51e-03
Epoch:30, train_loss: 1.74e-03
Epoch:31, train_loss: 6.64e-04
Epoch:32, train_loss: 9.62e-04
Epoch:33, train_l

" model.eval()\n    with torch.no_grad():\n        val_loss = 0.0\n        for val_inputs, val_targets in val_loader:\n            val_outputs = model(val_inputs)\n            val_loss += criterion(val_outputs, val_targets).item()\n   \n        val_loss /= len(dataset_2)\n    \n        print('Epoch: {}, Train Loss: {:.2e}, Val Loss: {:.2e}'.format(epoch+1, loss.item(), val_loss))"

In [24]:
# 保存模型
#torch.save(model_1, 'model_1.pkl') 
torch.save(model_2, 'model_2.pkl')

In [25]:
# # 保存模型
# torch.save(model_1, 'model_1.pkl') 
# torch.save(model_2, 'model_2.pkl')
# torch.save(model_senet, 'model_senet.pkl')

In [36]:
#模型预测
#model_1.eval()
model_2.eval()
#model_senet.eval()
with torch.no_grad():
   # output_1 = model_1(x_test)
    output_2 = model_2(x_test)
   # output_3 = model_senet(x_test)
#output_11 = torch.softmax(output_1,dim=1)   
output_22 = torch.softmax(output_2,dim=1)  
#output_33 = torch.softmax(output_3,dim=1)

In [37]:
output_11

tensor([[9.9999881e-01, 1.3559438e-07, 5.1877515e-07, 5.6808000e-07],
        [4.5929855e-07, 3.4132186e-06, 9.9999380e-01, 2.2540105e-06],
        [3.3575652e-08, 4.6551227e-07, 1.0491611e-06, 9.9999845e-01],
        ...,
        [4.5325575e-04, 2.1240468e-05, 9.9951971e-01, 5.7744760e-06],
        [9.9999225e-01, 3.5243220e-06, 2.5126205e-06, 1.7427968e-06],
        [6.8015790e-01, 2.5351407e-04, 1.1900196e-02, 3.0768836e-01]],
       device='cuda:0')

In [28]:
output_22

tensor([[9.9999952e-01, 2.0184212e-08, 3.3679385e-07, 1.0298263e-07],
        [2.5338358e-07, 2.5656545e-06, 9.9999404e-01, 3.1210839e-06],
        [4.1027299e-08, 7.0204869e-08, 4.6939203e-07, 9.9999940e-01],
        ...,
        [3.8767241e-05, 2.4874469e-06, 9.9994969e-01, 9.1163611e-06],
        [9.9999547e-01, 1.3343224e-06, 2.1217863e-06, 1.0328185e-06],
        [7.6255846e-01, 6.1165687e-05, 4.2383187e-02, 1.9499725e-01]],
       device='cuda:0')

In [38]:
# 模型融合
# predict = 0.5 * output_11 + 0.5 * output_22 
# predict
# predict = (output_11 + output_22 + output_33)/3 
# predict
predict = output_22 

In [39]:
np.set_printoptions(suppress=True)

In [40]:
predict_cpu = predict.cpu().numpy()
predict_cpu 

array([[0.9999995 , 0.00000002, 0.00000034, 0.0000001 ],
       [0.00000025, 0.00000257, 0.99999404, 0.00000312],
       [0.00000004, 0.00000007, 0.00000047, 0.9999994 ],
       ...,
       [0.00003877, 0.00000249, 0.9999497 , 0.00000912],
       [0.99999547, 0.00000133, 0.00000212, 0.00000103],
       [0.76255846, 0.00006117, 0.04238319, 0.19499725]], dtype=float32)

In [32]:
# 预测概率低于0.5的样本处理
numpy_array = predict_cpu 
for i in range(numpy_array.shape[0]):
    row = numpy_array[i]
    max_val = np.max(row)
    sorted_row = np.sort(row)
    second_max_val = sorted_row[-2]
    if max_val <= 0.5:
        if max_val - second_max_val >= 0.049:
            row[row != max_val] = 0
            row[row == max_val] = 1
            numpy_array[i] = row
        else:
            min_val = np.min(row)
            second_min_val = np.min(row[row != min_val])
            row[row == min_val] = 0
            row[row == second_min_val] = 0
            numpy_array[i] = row
numpy_array

array([[0.99999917, 0.00000008, 0.00000043, 0.00000034],
       [0.00000036, 0.00000299, 0.9999939 , 0.00000269],
       [0.00000004, 0.00000027, 0.00000076, 0.9999989 ],
       ...,
       [0.00024601, 0.00001186, 0.9997347 , 0.00000745],
       [0.99999386, 0.00000243, 0.00000232, 0.00000139],
       [0.7213582 , 0.00015734, 0.02714169, 0.2513428 ]], dtype=float32)

In [33]:
np.set_printoptions(suppress=True)
numpy_array_1=pd.DataFrame(numpy_array)
numpy_array_1.columns=["label_0","label_1","label_2","label_3"]
numpy_array_1.index=list(range(100000,120000))
numpy_array_1

label_0       label_1       label_2       label_3
100000  9.999992e-01  7.788930e-08  4.277845e-07  3.355313e-07
100001  3.563410e-07  2.989437e-06  9.999939e-01  2.687547e-06
100002  3.730148e-08  2.678586e-07  7.592766e-07  9.999989e-01
100003  9.999948e-01  1.566412e-06  1.588755e-06  2.017716e-06
100004  9.999650e-01  1.368527e-05  1.328572e-05  7.986689e-06
...              ...           ...           ...           ...
119995  9.999503e-01  7.238275e-06  3.629479e-05  6.169547e-06
119996  9.999979e-01  9.820301e-07  7.095744e-07  4.126110e-07
119997  2.460115e-04  1.186396e-05  9.997347e-01  7.445418e-06
119998  9.999939e-01  2.429322e-06  2.317203e-06  1.387808e-06
119999  7.213582e-01  1.573399e-04  2.714169e-02  2.513428e-01

[20000 rows x 4 columns]

In [34]:
numpy_array_1.loc[100000,"label_1"]

7.78893e-08

In [35]:
numpy_array_1.to_csv("test44.csv",index=True)